import Link from 'next/link'
import { ArrowUpRight, Clock3, Globe, HeartHandshake, Layers, MapPin, Target } from 'lucide-react'
import { FeatureCard, PageFrame, PageHero, SectionLabel, StatStrip } from '@/components/site-shell'

const roles = [
  { title: 'Product Engineer', dept: 'Engineering', location: 'Remote / Dhaka', type: 'Full-time', note: 'Ship the practice experience — fast, calm interfaces with honest feedback loops.' },
  { title: 'Design Engineer', dept: 'Design', location: 'Remote', type: 'Full-time', note: 'Own the feel of every interaction, from lesson flow to the little moments that build momentum.' },
  { title: 'Growth Marketer', dept: 'Marketing', location: 'Remote', type: 'Full-time', note: 'Turn a focused practice routine into a story people want to join and keep.' },
  { title: 'Customer Support Lead', dept: 'Support', location: 'Remote', type: 'Part-time', note: 'Be the calm voice behind the product and turn everyday questions into better lessons.' },
  { title: 'Data Analyst', dept: 'Analytics', location: 'Hybrid / Dhaka', type: 'Full-time', note: 'Find the signals in practice data that help people improve without overwhelm.' },
  { title: 'Content Writer', dept: 'Editorial', location: 'Remote', type: 'Contract', note: 'Write the practice scripts and guides that make every session useful and clear.' },
]

const benefits = [
  { icon: Globe, title: 'Work from anywhere', text: 'Remote-first with a small hub in Dhaka and async-friendly hours across time zones.' },
  { icon: Clock3, title: 'Flexible schedule', text: 'Own your day. We care about the work and the rhythm, not the exact clock-in time.' },
  { icon: HeartHandshake, title: 'Learning budget', text: 'Annual budget for courses, books, and conferences that help you grow.' },
  { icon: Layers, title: 'Equity in the studio', text: 'Every teammate gets a stake in the product they help build.' },
]

export default function CareersPage() {
  return <PageFrame><PageHero eyebrow="Careers / Build the studio" title={<>Work where practice <span className="text-primary">meets purpose.</span></>} description="We are a small, deliberate team building a calmer way to type. If you value focus, craft, and compounding progress, you will feel at home here." action="See open roles" />
    <StatStrip items={[{ value: '12', label: 'teammates' }, { value: '6', label: 'open roles' }, { value: 'Remote', label: 'first company' }]} />
    <section id="roles" className="mx-auto max-w-7xl px-5 py-16 md:px-8 md:py-24"><div className="mb-10 max-w-xl"><SectionLabel>Open positions</SectionLabel><h2 className="text-4xl font-semibold tracking-[-.04em] md:text-6xl">Come build momentum with us.</h2></div><div className="grid gap-4 md:grid-cols-2">{roles.map((role, index) => <article key={role.title} className="group flex flex-col justify-between rounded-3xl border border-border bg-card p-7 transition-colors hover:border-primary"><div className="flex items-start justify-between"><span className="font-mono text-xs text-muted-foreground">0{index + 1} / role</span><ArrowUpRight className="text-muted-foreground transition-transform group-hover:-translate-y-1 group-hover:translate-x-1" /></div><div className="mt-16"><span className="rounded-full border border-primary/30 bg-primary/10 px-3 py-1 font-mono text-[10px] uppercase tracking-wider text-primary">{role.type}</span><h3 className="mt-3 text-2xl font-medium tracking-tight">{role.title}</h3><p className="mt-1 text-xs text-muted-foreground">{role.dept}</p><p className="mt-4 text-sm leading-6 text-muted-foreground">{role.note}</p></div><div className="mt-8 flex flex-wrap items-center justify-between gap-3 border-t border-border pt-5 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1.5"><MapPin className="size-3.5 text-primary" />{role.location}</span><span className="inline-flex items-center gap-1.5"><Target className="size-3.5 text-primary" />Apply via hello@typely.co</span></div></article>)}</div></section>
    <section className="border-y border-border bg-muted/40"><div className="mx-auto max-w-7xl px-5 py-16 md:px-8 md:py-24"><SectionLabel>What we value</SectionLabel><div className="grid gap-4 md:grid-cols-2"><FeatureCard number="01" title="Calm over noise" text="We design for focus. Fewer notifications, clearer next steps, and interfaces that stay out of the way." /><FeatureCard number="02" title="Practice what you preach" text="We literally use the product. Every script, flow, and metric is shaped by our own daily typing." /><FeatureCard number="03" title="Small wins compound" text="We ship in small, honest increments and let steady improvement set the pace of the team." /><FeatureCard number="04" title="Users keep their data" text="Privacy is a feature, not a footnote. Progress stays local unless a user chooses otherwise." /></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 md:px-8 md:py-24"><SectionLabel>Perks</SectionLabel><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{benefits.map(({ icon: Icon, title, text }) => <div key={title} className="rounded-3xl border border-border bg-card p-6"><Icon className="mb-12 text-primary" /><h3 className="font-medium">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div>)}</div></section>
    <section className="border-t border-border bg-muted/40"><div className="mx-auto max-w-7xl px-5 py-16 md:px-8 md:py-24"><div className="rounded-3xl bg-foreground p-8 text-background md:p-14"><div className="grid gap-10 lg:grid-cols-[1fr_.7fr] lg:items-end"><div><SectionLabel>Don't see your role?</SectionLabel><h2 className="text-4xl font-semibold tracking-[-.05em] md:text-6xl">Tell us how you want to help.</h2></div><div><p className="max-w-md leading-7 text-background/70">We're always open to sharp, curious people who care about craft. Send a note about what you'd build, and we'll read it personally.</p><Link href="/practice" className="mt-7 inline-flex items-center gap-2 rounded-full bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">Say hello <ArrowUpRight className="size-4" /></Link></div></div></div></div></section>
  </PageFrame>
}
