import Link from 'next/link'
import { ArrowRight, Check, Keyboard, LineChart, Sparkles } from 'lucide-react'
import { FeatureCard, PageFrame, SectionLabel } from '@/components/site-shell'
import { StatStrip } from '@/components/stat-strip'
import { FaqSection } from '@/components/faq'

export default function HomePage() {
  return <PageFrame>
    <section className="mx-auto max-w-7xl px-5 pb-16 pt-16 md:px-8 md:pb-24 md:pt-24"><div className="max-w-5xl"><SectionLabel>Typing practice, with a point of view</SectionLabel><h1 className="text-balance text-6xl font-semibold leading-[.9] tracking-[-.07em] md:text-[9rem]">Make every<br /><span className="text-primary">keystroke count.</span></h1><div className="mt-10 flex flex-col gap-5 sm:flex-row sm:items-center"><p className="max-w-md text-pretty leading-7 text-muted-foreground">Typely turns scattered practice into a calm, measurable routine for faster, more accurate work.</p><Link href="/practice" className="inline-flex w-fit items-center rounded-full bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">Open practice <ArrowRight className="ml-2" data-icon="inline-end" /></Link></div></div></section>
    <StatStrip items={[{ value: '15+', label: 'focused lessons' }, { value: '5', label: 'practice paths' }, { value: '100%', label: 'your data, held locally' }]} />
    <section className="mx-auto max-w-7xl px-5 py-16 md:px-8 md:py-24"><div className="mb-10 max-w-xl"><SectionLabel>One studio, many ways to improve</SectionLabel><h2 className="text-4xl font-semibold tracking-[-.04em] md:text-6xl">Practice the part that slows you down.</h2></div><div className="grid gap-4 md:grid-cols-3"><FeatureCard number="01" title="Build a baseline" text="Short beginner drills turn finger placement and rhythm into an automatic starting point." /><FeatureCard number="02" title="Train for real work" text="Practice product copy, customer notes, code-like syntax, and the words you actually type." /><FeatureCard number="03" title="See the pattern" text="Momentum, WPM, accuracy, and character-level signals show you what to repeat next." /></div></section>
    <section className="border-y border-border bg-muted/40"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-16 md:px-8 md:py-24 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><SectionLabel>Designed for momentum</SectionLabel><h2 className="text-4xl font-semibold tracking-[-.04em] md:text-6xl">Less dashboard. More doing.</h2></div><div className="grid gap-4 sm:grid-cols-3">{[{ icon: Keyboard, title: 'A clear next lesson' }, { icon: LineChart, title: 'Progress you can trust' }, { icon: Sparkles, title: 'Tiny wins, repeated' }].map(({ icon: Icon, title }) => <div key={title} className="card bg-background p-6"><div aria-hidden className="card-glow" /><div className="chip relative mb-10 size-12 transition-transform duration-300 group-hover:scale-110"><Icon className="size-5" /></div><p className="relative font-medium">{title}</p></div>)}</div></div></section>
    <FaqSection />
    <section className="mx-auto max-w-7xl px-5 py-16 md:px-8 md:py-24"><div className="rounded-3xl bg-foreground p-8 text-background md:p-14"><div className="grid gap-10 lg:grid-cols-[1fr_.7fr] lg:items-end"><div><SectionLabel>Ready when you are</SectionLabel><h2 className="text-4xl font-semibold tracking-[-.05em] md:text-6xl">Give your next ten minutes a job.</h2></div><div><ul className="flex flex-col gap-3 text-sm text-background/70"><li className="flex gap-2"><Check className="text-primary" />Choose a path that fits your goal</li><li className="flex gap-2"><Check className="text-primary" />Practice one lesson at a time</li><li className="flex gap-2"><Check className="text-primary" />Come back to your momentum</li></ul><Link href="/practice" className="mt-7 inline-flex rounded-full bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">Start a session</Link></div></div></div></section>
  </PageFrame>
}
