'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { BarChart3, Check, Clock3, Crosshair, Keyboard, Pause, Play, RotateCcw, Target, Trophy, Zap } from 'lucide-react'
import lessons from '@/data/lessons.json'

type Lesson = (typeof lessons)[number]
type Point = { time: number; wpm: number }
type CharacterStat = { correct: number; incorrect: number }
const categories = ['Beginner', 'Medium', 'Advanced', 'Numbers', 'Symbols'] as const

export function TypingApp() {
  const [category, setCategory] = useState<string>('Beginner')
  const [selected, setSelected] = useState(0)
  const [started, setStarted] = useState(false), [paused, setPaused] = useState(false), [finished, setFinished] = useState(false)
  const [input, setInput] = useState(''), [elapsed, setElapsed] = useState(0), [errors, setErrors] = useState(0)
  const [history, setHistory] = useState<Point[]>([{ time: 0, wpm: 0 }])
  const [records, setRecords] = useState<Record<string, { bestWpm: number; bestAccuracy: number; attempts: number; completed: boolean }>>({})
  const [chars, setChars] = useState<Record<string, CharacterStat>>({})
  const inputRef = useRef<HTMLInputElement>(null), startedAt = useRef(0), pausedAt = useRef(0)
  const visibleLessons = lessons.filter((lesson) => lesson.category === category)
  const lesson: Lesson = visibleLessons[selected] ?? visibleLessons[0]
  const accuracy = input.length ? Math.max(0, Math.round(((input.length - errors) / input.length) * 100)) : 100
  const wpm = elapsed > 0 ? Math.round((Math.max(0, input.length - errors) / 5) / (elapsed / 60)) : 0
  const progress = lesson ? Math.round((input.length / lesson.script.length) * 100) : 0
  const strong = useMemo(() => Object.entries(chars).filter(([, value]) => value.correct > value.incorrect).sort((a, b) => b[1].correct - a[1].correct).slice(0, 5), [chars])
  const weak = useMemo(() => Object.entries(chars).filter(([, value]) => value.incorrect > 0).sort((a, b) => b[1].incorrect - a[1].incorrect).slice(0, 5), [chars])

  useEffect(() => { const saved = localStorage.getItem('typely-records'); if (saved) setRecords(JSON.parse(saved)); const savedChars = localStorage.getItem('typely-characters'); if (savedChars) setChars(JSON.parse(savedChars)) }, [])
  useEffect(() => { if (!started || paused || finished) return; const timer = window.setInterval(() => { const next = Math.floor((Date.now() - startedAt.current) / 1000); setElapsed(next); if (next > 0 && next % 3 === 0) setHistory((items) => [...items.slice(-11), { time: next, wpm }]) }, 1000); return () => clearInterval(timer) }, [started, paused, finished, wpm])

  const reset = () => { setStarted(false); setPaused(false); setFinished(false); setInput(''); setElapsed(0); setErrors(0); setHistory([{ time: 0, wpm: 0 }]) }
  const start = () => { if (!started) startedAt.current = Date.now(); else if (paused) startedAt.current += Date.now() - pausedAt.current; setStarted(true); setPaused(false); inputRef.current?.focus() }
  const chooseCategory = (next: string) => { setCategory(next); setSelected(0); reset() }
  const onChange = (value: string) => {
    if (finished || paused) return; if (!started) start(); const index = value.length - 1; const expected = lesson.script[index]; const actual = value[index]
    if (value.length > input.length) { setChars((all) => { const old = all[actual] ?? { correct: 0, incorrect: 0 }; const next = { ...all, [actual]: { correct: old.correct + (actual === expected ? 1 : 0), incorrect: old.incorrect + (actual === expected ? 0 : 1) } }; localStorage.setItem('typely-characters', JSON.stringify(next)); return next }); if (actual !== expected) setErrors((count) => count + 1) }
    setInput(value); if (value.length >= lesson.script.length) { setFinished(true); const old = records[lesson.id] ?? { bestWpm: 0, bestAccuracy: 0, attempts: 0, completed: false }; const next = { ...records, [lesson.id]: { bestWpm: Math.max(old.bestWpm, wpm), bestAccuracy: Math.max(old.bestAccuracy, accuracy), attempts: old.attempts + 1, completed: true } }; setRecords(next); localStorage.setItem('typely-records', JSON.stringify(next)) }
  }
  if (!lesson) return null
  const currentRecord = records[lesson.id]
  const totalCompleted = Object.values(records).filter((record) => record.completed).length

  return <main className="min-h-screen bg-background text-foreground">
    <header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 md:px-8"><a href="/" className="flex items-center gap-3 font-mono text-sm font-bold tracking-[0.2em]"><span className="grid size-8 place-items-center rounded-lg bg-primary text-primary-foreground">T</span> typely</a><nav className="hidden gap-7 text-sm text-muted-foreground md:flex"><a href="/product">Product</a><a href="/pricing">Pricing</a><a href="/integrations">Integrations</a><a href="/exam">Exam</a><a href="/careers">Careers</a><a href="/customers">Customers</a><a href="/resources">Resources</a></nav><span className="rounded-full border border-border px-4 py-2 text-xs text-muted-foreground">{totalCompleted}/{lessons.length} lessons done</span></header>
    <section id="top" className="mx-auto max-w-7xl px-5 pb-14 pt-14 md:px-8 md:pt-24"><div className="grid gap-8 lg:grid-cols-[1.2fr_.8fr] lg:items-end"><div><motion.p initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="mb-5 font-mono text-xs uppercase tracking-[.2em] text-primary">Your typing studio</motion.p><motion.h1 initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="max-w-3xl text-balance text-5xl font-semibold leading-none tracking-[-.06em] md:text-8xl">Build speed that <span className="text-primary">sticks.</span></motion.h1></div><p className="max-w-sm text-pretty leading-7 text-muted-foreground lg:justify-self-end">Choose a focused lesson, practice what you want, and keep a real record of your momentum.</p></div></section>
    <section id="practice" className="border-y border-border bg-muted/30"><div className="mx-auto max-w-7xl px-5 py-10 md:px-8"><div className="mb-6 flex items-end justify-between"><div><p className="mb-2 font-mono text-xs uppercase tracking-[.18em] text-muted-foreground">01 / Practice library</p><h2 className="text-2xl font-semibold tracking-tight">Pick your path</h2></div><Keyboard className="size-5 text-primary" /></div><div className="mb-6 flex flex-wrap gap-2">{categories.map((item) => <button key={item} onClick={() => chooseCategory(item)} className={`rounded-full border px-4 py-2 text-sm transition-colors ${category === item ? 'border-primary bg-primary text-primary-foreground' : 'border-border bg-background hover:border-primary'}`}>{item}</button>)}</div><div className="grid gap-3 md:grid-cols-3">{visibleLessons.map((item, index) => <motion.button key={item.id} onClick={() => { setSelected(index); reset() }} whileHover={{ y: -3 }} className={`rounded-2xl border p-5 text-left ${selected === index ? 'border-primary bg-primary/10' : 'border-border bg-background'}`}><div className="mb-8 flex justify-between font-mono text-[10px] uppercase tracking-wider text-muted-foreground"><span>{item.category}</span><span>{item.duration}</span></div><h3 className="mb-2 font-medium">{item.title}</h3><p className="text-sm leading-6 text-muted-foreground">{item.description}</p><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary transition-all" style={{ width: `${records[item.id]?.completed ? 100 : 0}%` }} /></div></motion.button>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-12 md:px-8 md:py-20"><div className="mb-7 flex items-end justify-between"><div><p className="mb-2 font-mono text-xs uppercase tracking-[.18em] text-muted-foreground">02 / Live workspace</p><h2 className="text-2xl font-semibold tracking-tight">{lesson.title}</h2></div><span className="font-mono text-sm text-muted-foreground">{elapsed}s / {lesson.duration}</span></div><div className="mb-4 h-3 overflow-hidden rounded-full bg-muted" aria-label="Lesson progress"><motion.div className="h-full rounded-full bg-primary" animate={{ width: `${progress}%` }} transition={{ type: 'spring', stiffness: 120, damping: 20 }} /></div><div className="mb-8 flex justify-between text-xs text-muted-foreground"><span>{progress}% complete</span><span>{currentRecord?.attempts ?? 0} attempts</span></div><div className="rounded-3xl border border-border bg-card p-5 shadow-xl md:p-8"><div className="mb-8 flex flex-wrap items-center gap-3"><button onClick={started && !paused ? () => { pausedAt.current = Date.now(); setPaused(true) } : start} className="inline-flex items-center gap-2 rounded-full bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground">{started && !paused ? <Pause /> : <Play />} {started && !paused ? 'Pause' : paused ? 'Resume' : 'Start typing'}</button><button onClick={reset} className="inline-flex items-center gap-2 rounded-full border border-border px-4 py-2.5 text-sm text-muted-foreground"><RotateCcw /> Restart</button><span className="ml-auto text-xs text-muted-foreground">{finished ? 'Session complete' : paused ? 'Paused' : started ? 'In progress' : 'Ready when you are'}</span></div><div onClick={() => inputRef.current?.focus()} className="relative min-h-48 cursor-text rounded-2xl border border-border bg-background p-5 font-mono text-xl leading-[2] tracking-tight md:p-8 md:text-2xl">{[...lesson.script].map((char, index) => <span key={`${char}-${index}`} className={index < input.length ? input[index] === char ? 'text-primary' : 'text-destructive underline decoration-2' : index === input.length && started && !paused ? 'border-l-2 border-primary' : 'text-muted-foreground/60'}>{char}</span>)}<input ref={inputRef} aria-label="Type the passage" value={input} onChange={(event) => onChange(event.target.value)} className="absolute inset-0 size-full opacity-0" autoCapitalize="off" autoCorrect="off" spellCheck={false} /></div><div className="mt-7 grid grid-cols-2 gap-3 md:grid-cols-4"><Metric icon={<Zap />} label="WPM" value={wpm} /><Metric icon={<Crosshair />} label="Accuracy" value={`${accuracy}%`} /><Metric icon={<Clock3 />} label="Time" value={`${elapsed}s`} /><Metric icon={<Check />} label="Errors" value={errors} /></div></div></section>
    <section id="progress" className="border-t border-border bg-muted/20"><div className="mx-auto max-w-7xl px-5 py-12 md:px-8"><p className="mb-2 font-mono text-xs uppercase tracking-[.18em] text-muted-foreground">03 / Real momentum</p><div className="mb-8 flex items-end justify-between"><h2 className="text-2xl font-semibold tracking-tight">Your progress, held for you.</h2><Trophy className="size-6 text-primary" /></div><div className="grid gap-5 lg:grid-cols-[1.5fr_1fr]"><div className="h-72 rounded-3xl border border-border bg-background p-4 md:p-6"><ResponsiveContainer width="100%" height="100%"><AreaChart data={history}><XAxis dataKey="time" tickLine={false} axisLine={false} /><YAxis hide /><Tooltip /><Area type="monotone" dataKey="wpm" stroke="var(--chart-1)" fill="var(--chart-1)" fillOpacity={.15} /></AreaChart></ResponsiveContainer></div><div className="grid grid-cols-2 gap-3"><Stat label="Lessons complete" value={`${totalCompleted}`} unit={`/ ${lessons.length}`} /><Stat label="Best speed" value={`${Math.max(0, ...Object.values(records).map((x) => x.bestWpm))}`} unit="WPM" /><Stat label="Best accuracy" value={`${Math.max(0, ...Object.values(records).map((x) => x.bestAccuracy))}`} unit="%" /><Stat label="Practice streak" value={totalCompleted ? '1' : '0'} unit="day" /></div></div></div></section>
    <section id="analytics" className="mx-auto max-w-7xl px-5 py-12 md:px-8"><div className="mb-7"><p className="mb-2 font-mono text-xs uppercase tracking-[.18em] text-muted-foreground">04 / Character analytics</p><h2 className="text-2xl font-semibold tracking-tight">Know your keyboard.</h2></div><div className="grid gap-4 md:grid-cols-2"><CharacterCard icon={<Target />} title="Strong characters" text="You are most accurate with" items={strong} empty="Complete a lesson to reveal your strengths." /><CharacterCard icon={<BarChart3 />} title="Needs practice" text="Spend a little time on" items={weak} empty="Mistyped characters will appear here." /></div></section>
    <footer className="mx-auto flex max-w-7xl justify-between border-t border-border px-5 py-8 text-xs text-muted-foreground md:px-8"><span className="font-mono tracking-widest">TYPELY / 2026</span><span>Practice with intention.</span></footer><AnimatePresence>{finished && <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="fixed bottom-6 right-6 rounded-2xl border border-primary bg-card px-5 py-4 shadow-xl"><div className="flex items-center gap-3"><Check className="text-primary" /><div><div className="font-medium">Lesson complete.</div><div className="text-xs text-muted-foreground">{wpm} WPM at {accuracy}% accuracy</div></div></div></motion.div>}</AnimatePresence>
  </main>
}
function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string | number }) { return <div className="rounded-2xl border border-border bg-background p-4"><div className="mb-4 flex items-center gap-2 text-xs text-muted-foreground"><span className="text-primary [&>svg]:size-4">{icon}</span>{label}</div><div className="font-mono text-2xl">{value}</div></div> }
function Stat({ label, value, unit }: { label: string; value: string; unit: string }) { return <div className="flex flex-col justify-between rounded-2xl border border-border bg-background p-4"><span className="text-xs text-muted-foreground">{label}</span><div><span className="font-mono text-2xl">{value}</span><span className="ml-1 text-xs text-muted-foreground">{unit}</span></div></div> }
function CharacterCard({ icon, title, text, items, empty }: { icon: React.ReactNode; title: string; text: string; items: [string, CharacterStat][]; empty: string }) { return <div className="rounded-3xl border border-border bg-card p-6"><div className="mb-6 flex items-center gap-3"><span className="text-primary">{icon}</span><div><h3 className="font-medium">{title}</h3><p className="text-sm text-muted-foreground">{text}</p></div></div>{items.length ? <div className="flex flex-wrap gap-3">{items.map(([character, stat]) => <div key={character} className="rounded-xl bg-muted px-4 py-3 text-center"><div className="font-mono text-xl">{character === ' ' ? 'space' : character}</div><div className="text-xs text-muted-foreground">{stat.correct} correct / {stat.incorrect} miss</div></div>)}</div> : <p className="text-sm text-muted-foreground">{empty}</p>}</div> }
